TRUNCATE TABLE dwh.fact_sales RESTART IDENTITY CASCADE;
TRUNCATE TABLE dwh.dim_sale RESTART IDENTITY CASCADE;
TRUNCATE TABLE dwh.dim_product_category RESTART IDENTITY CASCADE;
TRUNCATE TABLE dwh.dim_product RESTART IDENTITY CASCADE;
TRUNCATE TABLE dwh.dim_category RESTART IDENTITY CASCADE;
TRUNCATE TABLE dwh.dim_customer RESTART IDENTITY CASCADE;

-- dim_branch — справочник -> не очищаем
